#+title: Love for the Machine

It was 4 in the morning, and I was in time again. Dipping in and out of time is normal, my sense of it fades out of my brain every time the machine comes into view, and back in again whenever I look away or at any sort of timekeeping within the machine. Noise in the back of my head fades away and I begin to hear the ticking of digital hands in my clock - skeuomorphisms blending together like misremembered ancestors until the past is a single object, and I was out of time again and I began to go back into time. The ticking of mechanical hands in my brain keeps a vague and fuzzy counter in my head whose accuracy I do not have much confidence in, but it allows my eyes to zoom out of the machine to get a good look at it.

Standard government issue, and I could finally see its rough outlines after about 30 minutes or 2 days of not seeing it and I began to exit time before the mechanical hands ticked back into view. It's always hard to determine its composition, but the machine was vaguely artificial - I suppose that the machine has to be artificial, but much of the user experience feels deeply biological, like metronomes sinking their teeth into my eyes. I suppose strict timekeeping is instrumental to all human time-killing, but it's strange that to revive time I have to keep time, thus killing time. My eyes begin to zoom back into the machine, and its beauty and grace and ugliness are in full view. Mechanical ticking makes its last hurrah due to my acknowledgement of its exit before my sensory experience becomes the machine.

Oftentimes when using the machine I grow bored of its metronomes - a lot of the experiences are vaguely familiar to me, by design I suppose, but my mind wanders to meta-questions about the forms and functions of the machine. My eyes tend to zoom out slightly when doing this, but they're still zoomed in enough to benefit from the machine's fountains. Much of the machine's content is nebulous to me, the instant it enters I half-remember it as a generally positive experience. I think there was something about politics in there, some kind of commentary on escalation in the something region of the world that would take me a little over 3 seconds to find on an atlas, but don't quote me on that. Everything the machine comprises is shrouded in uncertainty and doubt, and I either accept it as the truth or give up on the concept that I will ever reach the truth and I began to fade out of any sense of time again and the mechanical hands jutted into view and I was in time again.

The machine's nature seemed to me more salient than ever before. It embraced me, fleshy cords pierced my skull and reminded me of the piercing headache that I always have but seem to forget about. Looking at it's anglerfish-like vague lights makes me dizzy without being fully immersed in them, so it's either I leap into the experiences that they present to me or I look away. The lights are encased in teeth, but teeth that I don't seem to have seen before, or teeth of a relative whose death has faded whatever physical regognitions I have of them, a micro-tragedy happening in a short enough timescale to be sad but a long enough timescale to not be recognized while it's happening. The machine was speckled with indicator lights and speedometers and flux capacitors and it gave me the vague idea of artificiality but there was no coherence in its design. Though most of us are laypeople, we understand when design has coherence placed into it without even understanding what coherence means in a technological context, but here only the vague idea of what coherence means has been placed into design.

It was 7 in the morning, and I was quickly fading out of time. I saw a gaping maw of teeth surrounding my field of vision before I became lost in time again. There was something about meta-questions about machines that I was thinking about - gah, whatever, it's not too important, and I have time to kill. 
