#+title: Day in the life of an 18-year-old Ivy League Dropout making $15k a day

(CW: some gore ahead)

My eyes twitch open like rusty gears jittering back to life. I'm sorrounded by fleshy edges connecting nodes with high degrees, some kind of inter-connecting web, and I'm suspended on them. Their embrace is stinging and acidic - spider's web that I was born on rather than captured into, so I'm largely used to it.

The edges are twisted around my neck, arms, and torso this time. They go taut, and my body twists and contorts to their whims - a body in motion subject to the weakness of his physical form. My arm is stretched back beyond the pivot point, making me look ready to weakly strike at whatever fortunate soul finds itself in front of me. The edges wrapping around my neck aren't of concern, I stopped breathing eons ago. My legs ouroboros around each other weakly, like they're not putting in enough effort to make my gore look pretty enough. My torso reflects its genetic origins by double-helixing to make me ready to spin as soon as these webs have mercy on me. Flesh balloons around the areas where the edges go taut.

5 A.M.; time to rise and grind. An ethereal claw emerges from a node and is ready to perform its sacred rites. My abdomen is scarred and naked and ready for the ritual performed the exact same way as 250 years prior. The claw begins flaying its flesh - its rightful possession, in no universe am I worthy of the flesh that it's taking back from me right now. The flaying continues regardless. My innards fly out left, then right, then left again. They fly into humble portals graciously given to the space underneath me, off to feed some pig somewhere.

My stomach is bare and perfect. other parts of my accursed body peek through the gaping cave created by the ritual - the ribs, for the most part; they're peeking into the cavity with hope that they too will meet the red light of the internet. The claw seems satisfied with its work and returns to its place in the aether, dematerializing.

New edges begin to cocoon my abdomen, the liquid that they secrete leaving mere hints of its existance in residual dribbles on my chest - leaving small red marks. It burns. My entire existance is engulfed in a virtual flame that presents itself in the form of potent orange acid that seeps into my everything and leaves its marks and sears my flesh like steak. Even a 30-minute lunch break would be preferable to the burning and searing and the acid has ingrained itself in the very primordial origin of my consciousness - the braim stem taking a nice long dip inside battery acid.

The edges slither away reluctantly, every planck length moved and every planck time experienced during this retreat optimally packs pain into my conscious experience, with careful thought put into scaling the design for a larger userbase. When they lose contact, I am left with the sight of a perfectly healthy, scarred stomach.

