#+title: One day after Another
(CW: violence)

Every day we push ourselves either closer to or farther away from our goal. Though I suppose that statement is obvious, and I suppose that the entire concept of a goal is some nebulous abstraction of the interaction between all three layers of our freudian psyche, but it makes sense as long as you don't think about it.

I looked in the mirror today, and I saw someone who wasn't quite me, but who could vaguely pass as me if he were the only person trying to be me alive right now. Me and whoever it is standing antiparallel in front of me, fighting to survive with bloodied and dirtied fingernails and teeth digging into whatever hold they could get onto the other. He looks strong - not a great sign for tonight, but I'll have to manage. 4 tired days and nights is the longest anyone has made it, I'd have to guess.

I worked today, and blank faces drifted about me, and they drilled robotic commands into me that I would execute with computational perfection, else I receive drastic consequence. It makes sense that the only person I think about is myself, compressing the entire existence of everyone else into one physical feature, but I suppose that there's no way of knowing whether they experience this same kind of consciousness that I do - Descartes and what not. That's another person, though - though also abstracted to one feature - though not physical - though a feature more emblematic of his thoughts and experiences and general consciousness than those of those not as ingrained into history as he is.

I've been fine-tuned into thinking solely about myself and how everything around me. If you think about it, it only makes sense - this is the best solution that would survive the most trials. Walking home today puts me on edge - it always puts me on edge - I'll have to test to see if I'm still worthy of existence. Approaching the front doorway, my keys faintly chimed an incoherent tune as he twisted them to allow entry into his apartment.

It was dark - like always - dark enough to dissolve any sense of knowledge about your surroundings. Though he knew where it was, he always had a general idea - it was the specifics that worried him: exact position, angle, force of impact, trajectory, etc. Turning a corner that he always had to feel out revealed a tall and sunken figure, though not excrutiatingly so. It was only slightly taller and looked as if it had not been outside for a week.

It began a primordial screech, and its hands twisted into spidery fists. It lept as if it knew that what was being allowed to happen was a betrayal of the natural order. He seemed only slightly prepared, stumbling out of drastic harm's way into mild harm's way. Its claw ripped at his shirt and dragged flesh with it. His counterattack was significantly more prepared than his initial reaction. With the boiling rage required for survival he began to beat over its head with his bare fists. Its pain was evident to all but him, with each muted thump filling the room with a piercing and nearly-human scream. It recollected itself during this whipping - knowing what was at stake - and snatched at one of his hands with its claws. The grip was filled with even greater rage than its cause, with a faded liquid seeping over and under the claw. He felt true, deep, undeniable, righteous, religious, primordial, lovecraftian, existential fear. With three vicious swipes to the neck, chest, and stomach it was over, and its corpse was limp in my now-weakening grasp. It slid under my hand and collapsed on the floor with all of the elegance of a drunk dancer - now more visible thanks to the lights slowly returning to normal. Cleaning this up is going to be such a pain, so I'll leave it to tomorrow me - it's friday, after all.

